platform :ios, '11.0'

target 'AcceptAPayment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AcceptAPayment
  pod 'Stripe'

  target 'AcceptAPaymentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AcceptAPaymentUITests' do
    # Pods for testing
  end

end
