platform :ios, '11.0'

target 'AcceptAPayment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AcceptAPayment
  pod 'Stripe', :git => 'https://github.com/thorsten-stripe/stripe-ios.git', :branch => 'davidme/pm-wechatpay-progress'

end
